osx_image: xcode9.3
dist: trusty
sudo: true

language: node_js
node_js: "9"
services:
  - docker

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker-compose build; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm install; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker-compose build; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run package-osx; fi

script:
  - docker-compose run compiler
